# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae7f93dcf5b51ea8e37364ad57a24591af66225e637e8f47756e89bc649a8b5151ca3a3f14a7719bf46a74f3125a946912623228d157601ba37909336d3407c6

test:
  secret_key_base: b4c76b1be4bb1fb0ab7beab4fde79eea2877e7cf94ec7a7d3f48b310d243a56c96309dc74b2c9bce1d2baa91d14c57d467a3decd65856e323403f8dd1af43a41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
